services:
  - type: web
    name: whatsapp-webhook
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: ACCESS_TOKEN
        value: EAAPNXagIZB84BO2UZB0Oy1fTDEGUAXTc5gNHaJT54q3Ak6tBZAZBLZBN4nNqhoVTcNcdREakSlHkgnaDsdFraZCRw4cQSOdLdhcmH8nKyXM6g8wpqeh039OjYRRkAerBNrxRmXFtdp3L1IQg78RJ7z5QM22bSlAhjhgY6sXESyr1zURg6MToksIbNKt3N40tUUQ16H6tGXnJMbmGLCgytfZBqFF
      - key: APP_ID
        value: 1070227064945614
      - key: APP_SECRET
        value: 8b19a484858db909726de6b8bfbc0f06
      - key: RECIPIENT_WAID
        value: +923336246663
      - key: VERSION
        value: v22.0
      - key: PHONE_NUMBER_ID
        value: 551555431385025
      - key: VERIFY_TOKEN
        value: my_secure_verify_token_12345
      - key: OPENAI_API_KEY
        value: 
      - key: OPENAI_ASSISTANT_ID
        value: 
