services:
  - type: web
    name: whatsapp-webhook
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: ACCESS_TOKEN
        value: EAAPNXagIZB84BOy30nGVVjZBTe1ZBK4AIvpjTe1hyZATwrwH7NZBca4aMLu8fz83bTurQnpLq81LaFWoDZBTvlx7qAuIXgp83ribdw36Gf86FfhD2xWd2RDP2zWeZA9c3jgVMkPSAlRkQopeXSwNx9DgZBEQhdXR2qZBrHmXoB40ZCeRF1xYOCGyZAwYlBtlVqnstcefgAQcdk6iZBv1xrMgjRscyDsI
      - key: APP_ID
        value: 1070227064945614
      - key: APP_SECRET
        value: 8b19a484858db909726de6b8bfbc0f06
      - key: RECIPIENT_WAID
        value: +923336246663
      - key: VERSION
        value: v22.0
      - key: PHONE_NUMBER_ID
        value: 551555431385025
      - key: VERIFY_TOKEN
        value: my_secure_verify_token_12345
      - key: OPENAI_API_KEY
        value: 
      - key: OPENAI_ASSISTANT_ID
        value: 
